masti_back/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('video_call.urls')),
    path('accounts/', include('allauth.urls')),
    # path('accounts/', include('allauth.socialaccount.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video_call/urls.py
from django.urls import path
from .views import home, login_view, register, logout_view, profile

urlpatterns = [
    path('', home, name='home'),
    path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile, name='profile'),
]

video_call/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class Account(AbstractUser):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]
    bio = models.CharField(max_length=50)
    gender =  models.CharField(max_length=1, choices=GENDER_CHOICES)
    profile_picture = models.ImageField(upload_to='profile_picture')
    dob = models.DateField(null=True, blank=True)

    class Meta:
        verbose_name = 'Account'

video_call/views.py
from django.shortcuts import render, redirect
from .models import Account
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required



@login_required(login_url='/login')
def home(request):
    return render(request, 'index.html')


def login_view(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if not user:
            return render(request, 'login.html', {'msg': 'Please enter correct username or password.'})
        login(request, user)
        return redirect('home')
    return render(request, 'login.html')


def register(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        username = request.POST.get('username')
        gender = request.POST.get('gender')
        password = request.POST.get('password')
        dob = request.POST.get('dob')

        if not fname or not lname or not username or not gender or not password or not dob:
            return render(request, 'register.html', {'msg': 'Something went wrong.'})

        account, created = Account.objects.get_or_create(username=username)
        if not created:
            return render(request, 'register.html', {'msg': 'Already user exists with this username.'})

        account.first_name = fname
        account.last_name = lname
        account.gender = gender
        account.dob = dob
        account.set_password(password)
        account.save()
        return redirect('login')
    return render(request, 'register.html')


def logout_view(request):
    if not request.user.is_authenticated:
        return redirect('login')
    logout(request)
    return redirect('login')


@login_required(login_url='/login')
def profile(request):
    if request.method == 'POST':
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        dob = request.POST.get('dob')
        gender = request.POST.get('gender')
        if not fname or not lname or not gender or not dob:
            return render(request, 'profile.html', {'msg': 'Something went wrong.'})

        request.user.first_name = fname
        request.user.last_name = lname
        request.user.dob = dob
        request.user.gender = gender
        request.user.save()
        return render(request, 'profile.html', {'msg': 'Profile updated successfully.'})
    return render(request, 'profile.html')

video_call/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load dob %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>It's Masti Time</title>
</head>
<body>
    <div class="heading">
        <h1 class="text-center"><a href="/">It's Masti Time</a></h1>
        <div>
            {% if request.user.is_authenticated %}
            <input hidden id="username" value="{{request.user.username}}">
            {% with age=request.user.dob|calculate_age %}
                <input hidden id="age" value="{{age}}">
            {% endwith %}
            <input hidden id="gender" value="{{request.user.get_gender_display}}">
            <div class="profile">
                <div class="mx-5">
                    <a href="/profile">
                        {% if request.user.profile_picture %}
                            <img src="/media/{{request.user.profile_picture}}" />
                        {% else %}
                            {% if request.user.gender == 'O' %}
                                <img src="{% static 'image/o.jpg' %}" />
                            {% elif request.user.gender %}
                                {% with age=request.user.dob|calculate_age %}
                                    {% if age <= 18 %}
                                        {% if request.user.gender == 'M' %}
                                            <img src="{% static 'image/b1.jpg' %}" />
                                        {% else %}
                                            <img src="{% static 'image/g1.jpg' %}" />
                                        {% endif %}
                                    {% elif age > 18 and age <= 30 %}
                                        {% if request.user.gender == 'M' %}
                                            <img src="{% static 'image/b2.jpg' %}" />
                                        {% else %}
                                            <img src="{% static 'image/g2.jpg' %}" />
                                        {% endif %}
                                    {% elif age > 18 and age > 30 %}
                                        {% if request.user.gender == 'M' %}
                                            <img src="{% static 'image/b3.jpg' %}" />
                                        {% else %}
                                            <img src="{% static 'image/g3.jpg' %}" />
                                        {% endif %}
                                    {% endif %}
                                {% endwith %}
                            {% endif %}
                        {% endif %}
                    </a>
                </div>
                <a href="/logout">Logout</a>
            </div>
            {% else %}
                <a href="/login">Login</a>
                <span>|</span>
                <a href="/register">Register</a>
            {% endif %}
        </div>
    </div>
    {% block body %}{% endblock body %}
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
    <script>{% block js %}{% endblock js %}</script>
</body>
</html>

video_call/templates/index.html
{% extends 'base.html' %}
{% block body %}
    <div id="main">
        <div class="video-call">
            <div class="peer other-peer">
                <p class="text-center" id="other-username">Finding...</p>
                <div class="frame">
                    <svg xmlns="http://www.w3.org/2000/svg" id="skip" width="50" height="50" fill="currentColor" class="bi bi-skip-forward" viewBox="0 0 16 16">
                        <path d="M15.5 3.5a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-1 0V8.752l-6.267 3.636c-.52.302-1.233-.043-1.233-.696v-2.94l-6.267 3.636C.713 12.69 0 12.345 0 11.692V4.308c0-.653.713-.998 1.233-.696L7.5 7.248v-2.94c0-.653.713-.998 1.233-.696L15 7.248V4a.5.5 0 0 1 .5-.5M1 4.633v6.734L6.804 8zm7.5 0v6.734L14.304 8z"/>
                    </svg>
                    <video autoPlay id="other-user" src=""></video>
                    <div class="loader" id="other-loader"></div>
                </div>
            </div>
            <div class="peer">
                <p class="text-center" id="self-username">Loading...</p>
                <div class="frame">
                    <video autoPlay id="self-user" src=""></video>
                    <div class="loader" id="self-loader"></div>
                </div>
            </div>
            <div id="start-btn">
                <button id="start">Start</button>
            </div>
        </div>
    </div>
{% endblock body %}

video_call/templates/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% block body %}
<div>
    <h1 class="text-center current">Login</h1>
    <form id="login-form" class="my-3 text-center" accept="/login" method="post">
        {% csrf_token %}
        <div class="text-center my-3">
            <input class="mx-3" name="username" id="username" placeholder="Username" />
            <input class="mx-3" name="password" type="password" id="password" placeholder="Password" />
        </div>
        <button class="my-2" type="submit">Submit</button>
    </form>
    <form action="{% provider_login_url 'google' %}" method="GET" class="google-login-form">
        <button type="submit" class="google-login-button">
            <img src="https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg" alt="Google Logo"
                class="google-logo">
            <span>Login with Google</span>
        </button>
    </form>
</div>
{% endblock body %}
{% block js %}
let msg = "{{msg}}"
if (msg){
alert(msg);
}
{% endblock js %}

video_call/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% load dob %}
{% block body %}
<div>
    <h1 class="text-center current">Profile</h1>
    <div class="profile-view text-center">
        <div class="profile-picture">
            {% if request.user.profile_picture %}
                <img src="/media/{{request.user.profile_picture}}" />
            {% else %}
                {% if request.user.gender == 'O' %}
                    <img src="{% static 'image/o.jpg' %}" />
                {% else %}
                    {% with age=request.user.dob|calculate_age %}
                        {% if age <= 18 %}
                            {% if request.user.gender == 'M' %}
                                <img src="{% static 'image/b1.jpg' %}" />
                            {% else %}
                                <img src="{% static 'image/g1.jpg' %}" />
                            {% endif %}
                        {% elif age > 18 and age <= 30 %}
                            {% if request.user.gender == 'M' %}
                                <img src="{% static 'image/b2.jpg' %}" />
                            {% else %}
                                <img src="{% static 'image/g2.jpg' %}" />
                            {% endif %}
                        {% elif age > 18 and age > 30 %}
                            {% if request.user.gender == 'M' %}
                                <img src="{% static 'image/b3.jpg' %}" />
                            {% else %}
                                <img src="{% static 'image/g3.jpg' %}" />
                            {% endif %}
                        {% endif %}
                    {% endwith %}
                {% endif %}
            {% endif %}
        </div>
        <div class="username">{{request.user.username}}</div>
        <div id="user-details">
            <div class="user-details my-4">
                <div>First Name</div>
                <div>{{request.user.first_name}}</div>
            </div>
            <div class="user-details my-4">
                <div>Last Name</div>
                <div>{{request.user.last_name}}</div>
            </div>
            <div class="user-details my-4">
                <div>DOB</div>
                <div>{{request.user.dob|date:'d N Y'}}</div>
            </div>
            <div class="user-details my-4">
                <div>Gender</div>
                <div>{{request.user.get_gender_display}}</div>
            </div>
            <button id="edit-profile">Edit</button>
        </div>
        <form id="profile-form" style="display: none;" class="register-form my-3" accept="/profile" method="post">
            {% csrf_token %}
            <div class="text-center my-3">
                <input class="mx-3" name="fname" value="{{request.user.first_name}}" id="fname" placeholder="First Name"/>
                <input class="mx-3" name="lname" value="{{request.user.last_name}}" id="lname" placeholder="Last Name"/>
            </div>
            <div class="text-center my-3">
                <input class="mx-3" type="date" value="{{request.user.dob|date:'Y-m-d'}}" name="dob" id="dob"/>
                <select class="mx-3" name="gender" id="gender">
                    <option {% if request.user.gender == "M" %}selected{% endif %} value="M">Male</option>
                    <option {% if request.user.gender == "F" %}selected{% endif %} value="F">Female</option>
                    <option {% if request.user.gender == "O" %}selected{% endif %} value="O">Other</option>
                </select>
            </div>
            <button class="my-2" type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock body %}
{% block js %}
let msg = "{{msg}}"
if (msg){
    alert(msg);
    window.location.href = '/profile';
}
{% endblock js %}

video_call/templates/register.html
{% extends 'base.html' %}
{% load socialaccount %}
{% block body %}
<div class="register-view">
    <h1 class="text-center current">Register</h1>
    <form id="register-form" class="register-form my-3" accept="/register" method="post">
        {% csrf_token %}
        <div class="text-center my-3">
            <input class="mx-3" name="fname" id="fname" placeholder="First Name"/>
            <input class="mx-3" name="lname" id="lname" placeholder="Last Name"/>
        </div>
        <div class="text-center my-3">
            <input class="mx-3" name="username" id="username" placeholder="Username"/>
            <select class="mx-3" name="gender" id="gender">
                <option disabled selected value="">Select gender</option>
                <option value="M">Male</option>
                <option value="F">Female</option>
                <option value="O">Other</option>
            </select>
        </div>
        <div class="text-center my-3">
            <input class="mx-3" name="password" id="password" type="password" placeholder="Password"/>
            <input class="mx-3" name="cpassword" id="cpassword" type="password" placeholder="Confirm Password"
            />
        </div>
        <div class="text-center my-3 dob">
            <label for="dob"><b>DOB</b></label>
            <input class="mx-3" name="dob" id="dob" type="date"/>
        </div>
        <button class="my-2" type="submit">Submit</button>
    </form>
    <form action="{% provider_login_url 'google' %}" method="GET" class="google-login-form">
        <button type="submit" class="google-login-button">
            <img src="https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg" alt="Google Logo"
                class="google-logo">
            <span>Register with Google</span>
        </button>
    </form>
</div>
{% endblock body %}
{% block js %}
let msg = "{{msg}}"
if (msg){
    alert(msg);
}
{% endblock js %}